### ISSUE TITLE
2 small bugs

### ISSUE THREAD

**Issue by 3ThumbsUp** [valsou/neoretro#13]
This is the best them for Pegasus by far. I've found two small bugs though.

If you enable Show "All Games" collection in settings, then when you scroll through different systems in the "Games View" one collection is always missing. It seems like "All Games" is replacing the last collection instead of being added as an extra collection.

Furthermore, it seems like when you go through collections in the "Games View" using the triggers they are sorted in the opposite order as in the "collection View". I would expect that right trigger is next system and left trigger is previous system, but it's the other way around.

**Comment by valsou** [comment]
Hi,

i'm currently rewriting the theme and will close your issue in favor of the new version; i won't push any fix for the current version. No release date yet, around April seems reasonable.

For your second issue you can edit `Games/Games.qml` :
- line 551 rename `isPageDown` to `isPageUp`
- ine 563 rename `isPageUp` to `isPageDown`

Feel free to reopen the issue if you have any questions.
