### ISSUE TITLE
Cycling through game lists with triggers is too sensitive

### ISSUE THREAD

**Issue by iwubcode** [valsou/neoretro#4]
When cycling through the platforms with the triggers, it seemed very sensitive.  It'd be nice if it could be slowed down

**Comment by B4rabbas** [comment]
Same for me.

**Comment by valsou** [comment]
Hi,

i close this issue in favor of a new version of the theme that will be released very soon. I won't push any fix for the current one.

I think that triggers are badly interpreted by Qt...
Either way i will be careful with the triggers for the next version and you will be able to reopen this issue if that still does not work.
