### ISSUE TITLE
No Image For Virtual Boy

### ISSUE THREAD

**Issue by ravensvoice** [valsou/neoretro#9]
Love this theme but I just added a Collection for Virtual Boy and there is no big splash image (like Crash on the Playstation on in this image: https://raw.githubusercontent.com/valsou/neoretro/readme_assets/assets/neoretro_v01_collections.jpg). Any possibiliy of adding one?

Thanks!

**Comment by valsou** [comment]
Hi,

assets added (71975c8c35a7cfd90ade544acce2aa8cd3c6113f). Didn't have a lot inspiration for the background, sorry. You can modify it replacing `virtualboy.jpg` file in `/assets/collections/bg`.

Thank you for the message.
